INSERT INTO book_category(name) VALUES
('Aventura'),
('Agricultura'),
('Alimentación'),
('Alquimia'),
('Animales'),
('Antropología'),
('Arquitectura'),
('Arte'),
('Astronomía'),
('Aves'),
('Biografía'),
('Botánica'),
('Ciencia'),
('Ciencia Ficción'),
('Cómics'),
('Criminología'),
('Cultura'),
('Deportes'),
('Derecho'),
('Diseño'),
('Economía'),
('Educación'),
('Ecología'),
('Electrónica'),
('Filosofía'),
('Ficción'),
('Fotografía'),
('Gastronomía'),
('Geografía'),
('Geología'),
('Historia'),
('Historia del Arte'),
('Idiomas'),
('Informática'),
('Ingeniería'),
('Ingeniería Civil'),
('Ingeniería Industrial'),
('Ingeniería Mecánica'),
('Ingeniería Química'),
('Juvenil'),
('Literatura Clásica'),
('Literatura Contemporánea'),
('Literatura Infantil'),
('Literatura Juvenil'),
('Magia'),
('Matemáticas'),
('Medicina'),
('Mitología'),
('Música'),
('Nanotecnología'),
('Naturaleza'),
('No Ficción'),
('Novela Negra'),
('Novela Romántica'),
('Oceanografía'),
('Océanos'),
('Odiseas'),
('Odontología'),
('Paleontología'),
('Poesía'),
('Política'),
('Psicología'),
('Química'),
('Religión'),
('Revistas'),
('Robótica'),
('Salud'),
('Sociología'),
('Software'),
('Tecnología'),
('Teatro'),
('Telecomunicaciones'),
('Terapias'),
('Viajes'),
('Videojuegos'),
('Zoología'),
('Antigüedades'),
('Arquitectura Moderna'),
('Astronomía Aplicada'),
('Ciencia Ambiental'),
('Ciencia de Datos'),
('Ciencias Sociales'),
('Cómputo'),
('Cultura Popular'),
('Derechos Humanos'),
('Diseño Gráfico'),
('Ecología Marina'),
('Educación Especial'),
('Educación Infantil'),
('Educación Superior'),
('Electrónica Industrial'),
('Filosofía Contemporánea'),
('Fotografía Artística'),
('Historia Contemporánea'),
('Historia de México'),
('Historia Medieval'),
('Ingeniería Eléctrica'),
('Ingeniería en Sistemas'),
('Ingeniería Mecatrónica'),
('Ingeniería Nuclear'),
('Lingüística'),
('Matemática Aplicada'),
('Medicina Interna'),
('Medicina Preventiva'),
('Mitología Griega'),
('Mitología Romana'),
('Neurociencia');
